### ISSUE TITLE
[BUG] 请求地址编码

### ISSUE THREAD

**Issue by HoshinoSuzumi** [ovojs/OvO#2]
![image](https://user-images.githubusercontent.com/26276464/124730576-118aa080-df44-11eb-80fa-5ab74ebfb654.png)

URL 中的 ?&=/ 没有必要 URLEncode

以上

**Comment by HoshinoSuzumi** [comment]
部分 web server 似乎无法正确解析被编码过的 url 查询

**Comment by Mivinci** [comment]
Thanks for your feedback. That was a mistake of mine. It will be fixed in the next minor version.
