### ISSUE TITLE
[BUG] Reply 未向后端传递 cid

### ISSUE THREAD

**Issue by HoshinoSuzumi** [ovojs/OvO#4]
![I~KA3FR0~8__4NT6IYZ LU7](https://user-images.githubusercontent.com/26276464/124744869-c6778a00-df51-11eb-9e20-dd341274c33e.png)
![_E1@14`}ZHGL(1GQ86WSKM2](https://user-images.githubusercontent.com/26276464/124744886-c9727a80-df51-11eb-95df-5a27d779578a.png)

如题

**Comment by Mivinci** [comment]
Fixed in previous versions.
