### ISSUE TITLE
[Future] 自定义表情包支持

### ISSUE THREAD

**Issue by DejavuMoe** [ovojs/OvO#8]
[BQB](https://github.com/DejavuMoe/BQB) 提供表情 Map ![](https://cdn.jsdelivr.net/gh/DejavuMoe/BQB@1.0.0/Coolapk/053.png)

**Comment by Mivinci** [comment]
感谢建议 但当前实例化 OvO 时 可以传入 emoji 参数 该参数为表情资源的地址

**Comment by Mivinci** [comment]
@DejavuMoe 感谢建议 但当前实例化 OvO 时 可以传入 emoji 参数 该参数为表情资源的地址
